<?php

/**
 * Implements hook_menu().
 *
 * Add page with the map.
 */
function mapez_map_menu() {

  $items['mapez_map'] = array(
    'title' => 'Mapez - find your dream house.',
    'page callback' => 'mapez_map_render',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback.
 *
 * Render initial map with presaved filters.
 */
function mapez_map_render() {
  $results = mapez_search_render_results();
  return $results['rendered_map'] . $results['results_list'];
}

/**
 * Our own copy of leaflet_render_map to avoid incremental #id generation.
 */
function mapez_map_leaflet_render_map($map, $features = array(), $height = '400px') {
  $map_id = 'leaflet-map';
  drupal_add_library('leaflet', 'leaflet-drupal');

  // Allow map definitions to provide a default icon
  if (isset($map['icon']['iconUrl'])) {
    foreach ($features as &$feature) {
      if (!isset($feature['icon'])) {
        $feature['icon'] = $map['icon'];
      }
    }
  }

  $settings = array(
    'mapId' => $map_id,
    'map' => $map,
    'features' => $features,
  );

  drupal_add_js(array('leaflet' => array($settings)), 'setting');

  return theme('leaflet_map', array('map_id' => $map_id, 'height' => $height));
}
