<?php

/**
 * Implements hook_menu().
 *
 * Add page with the map.
 */
function mapez_map_menu() {

  $items['mapez_map'] = array(
    'title' => 'Mapez - find your dream house.',
    'page callback' => 'mapez_map_render',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback.
 *
 * Render initial map with presaved filters.
 */
function mapez_map_render() {
  $maps = leaflet_map_get_info();
  $offers = entity_load('node', FALSE, array('type' => 'offer'));
  $data = array();
  foreach ($offers as $offer) {
    if (!empty($offer->field_location)) {
      $points = leaflet_process_geofield($offer->field_location[LANGUAGE_NONE]);
      $points[0]['popup'] = drupal_render(node_view($offer, 'teaser'));
      $data = array_merge($data, $points);
    }
    $titles[] = $offer->title;
  }

  $default_map = mapez_map_leaflet_render_map($maps['OSM Mapnik'], $data, '400px');
  $default_list = theme('item_list', array('items' => $titles));
  return '<div id="leaflet-map-wrapper">' . $default_map . '</div>' .
         '<div class="results-list">' . $default_list . '</div>';
}

/**
 * Our own copy of leaflet_render_map to avoid incremental #id generation.
 */
function mapez_map_leaflet_render_map($map, $features = array(), $height = '400px') {
  $map_id = 'leaflet-map';
  drupal_add_library('leaflet', 'leaflet-drupal');

  // Allow map definitions to provide a default icon
  if (isset($map['icon']['iconUrl'])) {
    foreach ($features as &$feature) {
      if (!isset($feature['icon'])) {
        $feature['icon'] = $map['icon'];
      }
    }
  }

  $settings = array(
    'mapId' => $map_id,
    'map' => $map,
    'features' => $features,
  );

  drupal_add_js(array('leaflet' => array($settings)), 'setting');

  return theme('leaflet_map', array('map_id' => $map_id, 'height' => $height));
}
